name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
      - name: Docker build
        run: |
          sbt docker:publishLocal
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker
        env:
          REPOSITORY: snowplow/snowplow-bigquery-gcs-event-recovery
          TAG: ${{github.ref_name}}
        run: docker push $REPOSITORY:$TAG
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: ${{ contains(github.ref , '-') }}
